version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    open-pull-requests-limit: 20
    reviewers:
      - jentfoo
